# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  service-registry:
    build:
      context: .
      dockerfile: registry-service/Dockerfile
      target: development
    ports:
      - 8761:8761
    networks:
      - ticket-network
    develop:
      watch:
        - action: rebuild
          path: .
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
      target: development
    ports:
      - 8088:8088
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - ticket-network
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - service-registry
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/actuator/health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
      target: development
    ports:
      - 8000:8001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth-service:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - ticket-network
    depends_on:
      db-auth-service:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  db-auth-service:
    image: postgres:18-alpine
    restart: always
    volumes:
      - db-auth-service-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5433"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network

  ticket-service:
    build:
      context: .
      dockerfile: ticket-service/Dockerfile
      target: development
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ticket-service:5432/tickets_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - ticket-network
    depends_on:
      db-ticket-service:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  db-ticket-service:
    image: postgres:18-alpine
    restart: always
    volumes:
      - db-ticket-service-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tickets_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tickets_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network

volumes:
  db-data:
  db-ticket-service-data:
    driver: local
  db-auth-service-data:
    driver: local

networks:
  ticket-network:
    driver: bridge
