spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: ticket-service
            uri: lb://ticket-service
            predicates: 
              - Path=/api/movies/**, /api/hall/**, /api/showtimes/**, /api/tickets/**

server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/