spring:
 output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com:
      jrb: debug

jwt:
  secret: ${JWT_SECRET_KEY:temporaSecretKeyMustBeVeryLongToWorkWithHS256Algorithm}
  expiration: ${JWT_EXPIRATION_TIME:3600000}

eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}