spring:
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    com.jrb.ticket_service: debug

management:
  endpoints:
    web:
      exposure:
        include: health
        
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}